name: nips-interpretation
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - accelerate=1.5.2
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.18
  - aiosignal=1.3.2
  - alsa-lib=1.2.14
  - anyio=4.9.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - async-timeout=5.0.1
  - attrs=25.3.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.15
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.9
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.10
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.12
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - cpython=3.10.17
  - cuda-cudart=12.9.37
  - cuda-cudart_linux-64=12.9.37
  - cuda-nvrtc=12.9.41
  - cuda-nvtx=12.9.19
  - cuda-version=12.9
  - cudnn=8.9.7.29
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - datasets=3.6.0
  - dbus=1.13.6
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - frozenlist=1.6.0
  - fsspec=2025.3.0
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.13
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=11.2.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.30.2
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.36.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.4
  - libclang13=20.1.4
  - libcrc32c=1.1.2
  - libcublas=12.9.0.13
  - libcufft=11.4.0.6
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcurl=8.13.0
  - libcusolver=11.7.4.40
  - libcusparse=12.5.9.5
  - libdeflate=1.24
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.25.0
  - libgoogle-cloud-storage=2.25.0
  - libgrpc=1.62.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.4
  - liblzma=5.8.1
  - libmagma=2.7.2
  - libmagma_sparse=2.7.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.9.41
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.16.1
  - libopentelemetry-cpp-headers=1.16.1
  - libparquet=16.1.0
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libthrift=0.19.0
  - libtiff=4.7.0
  - libtorch=2.3.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.2
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=20.1.4
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.4.3
  - multiprocess=0.70.16
  - munkres=1.1.4
  - nb_conda_kernels=2.5.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nccl=2.26.5.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - notebook=7.4.2
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - orc=2.0.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - prometheus-cpp=1.2.4
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.3.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - qt6-main=6.9.0
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.36.2
  - regex=2024.11.6
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.24.0
  - s2n=1.4.16
  - safetensors=0.5.3
  - send2trash=1.8.3
  - setuptools=80.1.0
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.7
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2021.13.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.21.1
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.51.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.20.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
